# Vite App Name
frontend_name="${APP_NAME}-frontend"
deployment_name="${APP_NAME}-gcloud"
bucket_name="${PROJECT_ID}-bucket"
backend_bucket_name="${PROJECT_ID}-backend-bucket"
app_ip_name="${deployment_name}-ip"
loadbalancer_name="${deployment_name}-lb"
proxy_name="${loadbalancer_name}-proxy"
forwarding_rule_name="${deployment_name}-forwarding-rule"
managed_zone="${deployment_name}-zone"

printinfo "Project Variables:"
echo "PROJECT_ID: $PROJECT_ID"
echo "FRONTEND_NAME: $frontend_name"
echo "DEPLOYMENT_NAME: $deployment_name"
echo "BUCKET_NAME: $bucket_name"
echo "BACKEND_BUCKET_NAME: $backend_bucket_name"
echo "APP_IP_NAME: $app_ip_name"
echo "LOADBALANCER_NAME: $loadbalancer_name"
echo "PROXY_NAME: $proxy_name"
echo "FORWARDING_RULE_NAME: $forwarding_rule_name"
echo "MANAGED_ZONE: $managed_zone"
